on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: shaleenchughacr.azurecr.io
        username: ${{ secrets.acr_shaleenchughacr_username }}
        password: ${{ secrets.acr_shaleenchughacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t shaleenchughacr.azurecr.io/myakscluster:${{ github.sha }}
        docker push shaleenchughacr.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myakscluster0ad8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myakscluster0ad8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myakscluster0ad8
        container-registry-url: shaleenchughacr.azurecr.io
        container-registry-username: ${{ secrets.acr_shaleenchughacr_username }}
        container-registry-password: ${{ secrets.acr_shaleenchughacr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: myakscluster0ad8
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          shaleenchughacr.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth